package ir.transport_x.taxi.model

data class ServiceDataModel(
    var id: Int,
    var customerId: Int,
    var sourceAddressId: Int,
    var count: Int,
    var description: String,
    var fixedDescription: String,
    var carType: Int, // like economy....
    var stopTime: Int,
    var saveDate: String,
    var userId: Int,
    var driverId: Int,
    var finishDate: String,
    var voipId: String,
    var acceptDate: String,
    var price: String,
    var customerName: String,
    var phoneNumber: String,
    var mobile: String,
    var carTypeName: String,
    var sourceAddress: String,
    var destinationAddress: String,
    var priceService: String,
    var discount: String,
    var cancelCount: Int,
    var punishmentPrice: Int,
    var timeRequiredCancellation: Int,
    var cityId: Int,
    var serviceTypeId: Short,
    var voipLink: String,
)